# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHPublicKey',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField(unique=True)),
                ('md5', models.CharField(editable=False, max_length=256, unique=True)),
                ('sha256', models.CharField(editable=False, max_length=256, unique=True)),
                ('sha512', models.CharField(editable=False, max_length=256, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_sshpublickey', 'Can view public key'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='sshpublickey',
            unique_together=set([('name', 'owner')]),
        ),
    ]
