# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20161018_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_cn', models.CharField(editable=False, max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token')),
            ],
            options={
                'permissions': (('view_dockercert', 'Can view Docker Certificate'),),
            },
        ),
    ]
