# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('users', '0002_auto_20161018_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_cn', models.CharField(editable=False, max_length=32)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token')),
            ],
        ),
    ]
