# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


def forwards_func(apps, schema_editor):
    DockerCert = apps.get_model('users', 'DockerCert')
    db_alias = schema_editor.connection.alias
    DockerCert.objects.all().delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_dockercert'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('key', models.CharField(default=users.models._crypto_40_token, max_length=40, primary_key=True, serialize=False)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            code=forwards_func,
            reverse_code=reverse_func,
        ),
        migrations.AlterField(
            model_name='dockercert',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.APIToken'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='key',
            field=models.CharField(default=users.models._crypto_40_token, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
