# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161109_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshpublickey',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
