# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_project', 'Can view this project'),),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docker_ca_pem', models.TextField()),
                ('docker_cert_pem', models.TextField()),
                ('docker_key_pem', models.TextField()),
                ('unison_id_rsa', models.TextField()),
                ('host', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('docker_compose_file', models.TextField()),
                ('slug', models.CharField(editable=False, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'permissions': (('view_stack', 'Can view this stack'),),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='projects.Server'),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Stack'),
        ),
        migrations.AlterUniqueTogether(
            name='stack',
            unique_together=set([('owner', 'name')]),
        ),
    ]
