# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_server_unison_id_rsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='docker_cert_pem',
        ),
        migrations.RemoveField(
            model_name='server',
            name='docker_key_pem',
        ),
    ]
