# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161101_1229'),
        ('projects', '0003_stack_description'),
    ]

    operations = [
    ]
