# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Stack'),
        ),
    ]
